apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- config.yaml
- ingress.yaml
- hpa.yaml
- servicemonitor.yaml
- pdb.yaml
- priority.yaml
- backup.yaml

commonLabels:
  app: docmatrix
  component: api

namePrefix: docmatrix-

configMapGenerator:
- name: docmatrix-config
  behavior: create
  options:
    disableNameSuffixHash: true

vars:
- name: CONFIG_CHECKSUM
  objref:
    kind: ConfigMap
    name: docmatrix-config
    apiVersion: v1
  fieldref:
    fieldpath: metadata.uid 