apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: docmatrix-api
  labels:
    app: docmatrix
    component: api
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: docmatrix
      component: api 