apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: docmatrix-api
  labels:
    app: docmatrix
    component: api
    release: prometheus
spec:
  selector:
    matchLabels:
      app: docmatrix
      component: api
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
  namespaceSelector:
    any: true 