name: Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - '.github/workflows/docs.yml'
  pull_request:
    paths:
      - 'docs/**'
      - '.github/workflows/docs.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt
          pip install pytest pytest-cov requests

      - name: Run API endpoint tests
        env:
          API_BASE_URL: ${{ secrets.API_BASE_URL }}
          API_KEY: ${{ secrets.API_KEY }}
          TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
          TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
        run: |
          cd docs
          pytest tests/test_api_examples.py -v --cov=tests --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./docs/coverage.xml
          flags: api-tests
          name: codecov-umbrella
          fail_ci_if_error: true

  docs:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt

      - name: Build documentation
        run: |
          cd docs
          make html
          touch _build/html/.nojekyll

      - name: Check links
        run: |
          cd docs
          make linkcheck

      - name: Run doctests
        run: |
          cd docs
          make doctest

      - name: Deploy to GitHub Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
          force_orphan: true

      - name: Deploy to HostGator
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.HOSTGATOR_FTP_SERVER }}
          username: ${{ secrets.HOSTGATOR_FTP_USERNAME }}
          password: ${{ secrets.HOSTGATOR_FTP_PASSWORD }}
          local-dir: docs/_build/html/
          server-dir: public_html/docs/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/__pycache__/** 